### PR TITLE
Default to system perl and allow use of strawberry perl.

### PR DESCRIPTION
**Pull request by Alexhuszagh**
Now defaults to the system perl unless `CROSS_WINDOWS_PERL=1` is set, in which case use strawberry perl, which handles Windows paths.

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
This requires `cross` proper to forward environment variables starting with `CROSS_` to the container.

**Comment by Alexhuszagh** [comment]
Now that https://github.com/cross-rs/cross/pull/1073 has been merged, @Emilgardis, does this look good?

**Review by Emilgardis — APPROVED** [review]
lgtm!

**Pull request merged**
