### PR TITLE
Add python dependency for darwin.sh

### PR DESCRIPTION
**Pull request by 0xdeafbeef**

### CODE REVIEW

**Comment by Alexhuszagh** [comment]
Is this needed? Does it affect the builds? Remember that `install_packages` will be purged after the script is finished, so any transient dependencies will be removed. If you want Python installed in all Darwin images, you should probably place it in the Dockerfile itself.

**Comment by Alexhuszagh** [comment]
If your proposal is to add Python by default to all Darwin images, this might be a good idea for both Darwin and MSVC, since the images are already quite large and a Python install is quite small. Darwin images are ~1.9GB, and MSVC ones are ~8GB, while a full Python install is ~30MB. So we could easily justify that, but it would have to be done in a different manner.

**Comment by 0xdeafbeef** [comment]
> Is this needed? Does it affect the builds? From my builds, I don't remember it being required. If it's needed afterwards to use the toolchain, then we need a different solution. Remember that `install_packages` will be purged after the script is finished, so any transient dependencies will be removed. If you want Python installed in all Darwin images, you should probably place it in the Dockerfile itself.

Build without python fails
image

**Comment by Alexhuszagh** [comment]
Oh that's interesting, it didn't fail before. Let me test this just to be sure (we'll probably need to setup CI soon) and I'll merge this.

**Comment by 0xdeafbeef** [comment]
`MACOS_SDK_URL=https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz` (for test purposes)

**Comment by Alexhuszagh** [comment]
I'm removing that comment but I was using 10.7 earlier (since it's the latest my old Macbook Pro could use), but I'll try on a more recent one.

**Comment by Alexhuszagh** [comment]
It failed one `10.11` as well, so nice catch.

**Pull request merged**
